#!/usr/bin/env python3
"""
Latency Analysis Script for Spot Teleoperation Pipeline

This script analyzes the CSV files generated by the latency logger and provides
insights into the performance of the perception-decision-action pipeline.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import argparse
import os
import glob
from datetime import datetime


class LatencyAnalyzer:
    """Analyzes latency data from CSV files."""
    
    def __init__(self, csv_directory):
        self.csv_directory = csv_directory
        self.latency_data = None
        self.events_data = None
        
    def load_data(self):
        """Load latency and events data from CSV files."""
        # Find the most recent latency file
        latency_files = glob.glob(os.path.join(self.csv_directory, "spot_latencies_*.csv"))
        events_files = glob.glob(os.path.join(self.csv_directory, "spot_events_*.csv"))
        
        if not latency_files:
            raise FileNotFoundError(f"No latency CSV files found in {self.csv_directory}")
            
        # Use the most recent file
        latest_latency_file = max(latency_files, key=os.path.getctime)
        print(f"Loading latency data from: {latest_latency_file}")
        
        self.latency_data = pd.read_csv(latest_latency_file)
        
        if events_files:
            latest_events_file = max(events_files, key=os.path.getctime)
            print(f"Loading events data from: {latest_events_file}")
            self.events_data = pd.read_csv(latest_events_file)
            
        # Convert timestamps to datetime for better analysis
        if 'timestamp' in self.latency_data.columns:
            self.latency_data['datetime'] = pd.to_datetime(self.latency_data['timestamp'], unit='s')
            
        print(f"Loaded {len(self.latency_data)} complete cycles")
        
    def print_summary_statistics(self):
        """Print summary statistics of latency measurements."""
        if self.latency_data is None:
            raise ValueError("Data not loaded. Call load_data() first.")
            
        print("\n" + "="*60)
        print("SPOT TELEOPERATION LATENCY ANALYSIS")
        print("="*60)
        
        # Overall statistics
        print(f"\nTotal completed cycles: {len(self.latency_data)}")
        if 'mode' in self.latency_data.columns:
            mode_counts = self.latency_data['mode'].value_counts()
            print(f"Mode breakdown: {dict(mode_counts)}")
            
        # Latency statistics
        latency_columns = [
            'total_latency', 'perception_latency', 'decision_latency', 
            'execution_latency', 'finger_count_latency', 'wrist_tf_latency', 
            'yolo_detection_latency'
        ]
        
        print(f"\n{'Latency Type':<25} {'Mean (ms)':<12} {'Std (ms)':<12} {'Min (ms)':<12} {'Max (ms)':<12}")
        print("-" * 73)
        
        for col in latency_columns:
            if col in self.latency_data.columns:
                data = self.latency_data[col].dropna() * 1000  # Convert to ms
                if len(data) > 0:
                    print(f"{col.replace('_', ' ').title():<25} "
                          f"{data.mean():<12.1f} {data.std():<12.1f} "
                          f"{data.min():<12.1f} {data.max():<12.1f}")
                          
        # Success rate
        if 'success' in self.latency_data.columns:
            success_rate = self.latency_data['success'].value_counts(normalize=True).get(True, 0) * 100
            print(f"\nOverall success rate: {success_rate:.1f}%")
            
        # Command type breakdown
        if 'command_type' in self.latency_data.columns:
            print(f"\nCommand type distribution:")
            cmd_counts = self.latency_data['command_type'].value_counts()
            for cmd_type, count in cmd_counts.items():
                print(f"  {cmd_type}: {count} cycles")
                
    def plot_latency_distribution(self, save_path=None):
        """Plot latency distribution histograms."""
        if self.latency_data is None:
            raise ValueError("Data not loaded. Call load_data() first.")
            
        # Prepare data
        latency_columns = ['total_latency', 'perception_latency', 'decision_latency', 'execution_latency']
        available_columns = [col for col in latency_columns if col in self.latency_data.columns]
        
        if not available_columns:
            print("No latency columns found for plotting")
            return
            
        # Create subplots
        fig, axes = plt.subplots(2, 2, figsize=(15, 10))
        fig.suptitle('Spot Teleoperation Latency Distribution', fontsize=16, fontweight='bold')
        axes = axes.flatten()
        
        for i, col in enumerate(available_columns):
            if i >= len(axes):
                break
                
            data = self.latency_data[col].dropna() * 1000  # Convert to ms
            if len(data) == 0:
                continue
                
            ax = axes[i]
            ax.hist(data, bins=30, alpha=0.7, color='steelblue', edgecolor='black')
            ax.set_title(col.replace('_', ' ').title())
            ax.set_xlabel('Latency (ms)')
            ax.set_ylabel('Frequency')
            ax.grid(True, alpha=0.3)
            
            # Add statistics text
            mean_val = data.mean()
            std_val = data.std()
            ax.axvline(mean_val, color='red', linestyle='--', alpha=0.8, label=f'Mean: {mean_val:.1f}ms')
            ax.legend()
            
        # Hide unused subplots
        for i in range(len(available_columns), len(axes)):
            axes[i].set_visible(False)
            
        plt.tight_layout()
        
        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            print(f"Latency distribution plot saved to: {save_path}")
        else:
            plt.show()
            
    def plot_latency_timeline(self, save_path=None):
        """Plot latency over time."""
        if self.latency_data is None:
            raise ValueError("Data not loaded. Call load_data() first.")
            
        if 'datetime' not in self.latency_data.columns:
            print("Datetime column not available for timeline plot")
            return
            
        fig, ax = plt.subplots(figsize=(15, 8))
        
        # Plot total latency over time
        data = self.latency_data.dropna(subset=['total_latency'])
        if len(data) == 0:
            print("No total latency data available for timeline plot")
            return
            
        ax.scatter(data['datetime'], data['total_latency'] * 1000, alpha=0.6, s=30)
        ax.set_title('Total Latency Over Time', fontsize=14, fontweight='bold')
        ax.set_xlabel('Time')
        ax.set_ylabel('Total Latency (ms)')
        ax.grid(True, alpha=0.3)
        
        # Add trend line
        from scipy.stats import linregress
        timestamps_numeric = data['timestamp'].values
        latencies = data['total_latency'].values * 1000
        
        if len(timestamps_numeric) > 1:
            slope, intercept, r_value, p_value, std_err = linregress(timestamps_numeric, latencies)
            trend_line = slope * timestamps_numeric + intercept
            ax.plot(data['datetime'], trend_line, color='red', linestyle='--', alpha=0.8, 
                   label=f'Trend (R²={r_value**2:.3f})')
            ax.legend()
            
        plt.xticks(rotation=45)
        plt.tight_layout()
        
        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            print(f"Timeline plot saved to: {save_path}")
        else:
            plt.show()
            
    def compare_modes(self, save_path=None):
        """Compare latency between manual and semi-autonomous modes."""
        if self.latency_data is None:
            raise ValueError("Data not loaded. Call load_data() first.")
            
        if 'mode' not in self.latency_data.columns:
            print("Mode column not available for comparison")
            return
            
        modes = self.latency_data['mode'].unique()
        if len(modes) < 2:
            print(f"Only one mode found: {modes}")
            return
            
        fig, axes = plt.subplots(2, 2, figsize=(15, 10))
        fig.suptitle('Latency Comparison: Manual vs Semi-Autonomous', fontsize=16, fontweight='bold')
        axes = axes.flatten()
        
        latency_columns = ['total_latency', 'perception_latency', 'decision_latency', 'execution_latency']
        
        for i, col in enumerate(latency_columns):
            if i >= len(axes) or col not in self.latency_data.columns:
                continue
                
            ax = axes[i]
            
            # Create box plot
            mode_data = []
            mode_labels = []
            
            for mode in modes:
                data = self.latency_data[self.latency_data['mode'] == mode][col].dropna() * 1000
                if len(data) > 0:
                    mode_data.append(data)
                    mode_labels.append(f"{mode.title()} (n={len(data)})")
                    
            if mode_data:
                ax.boxplot(mode_data, labels=mode_labels)
                ax.set_title(col.replace('_', ' ').title())
                ax.set_ylabel('Latency (ms)')
                ax.grid(True, alpha=0.3)
                
        plt.tight_layout()
        
        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            print(f"Mode comparison plot saved to: {save_path}")
        else:
            plt.show()
            
    def generate_report(self, output_dir=None):
        """Generate a comprehensive latency analysis report."""
        if output_dir is None:
            output_dir = self.csv_directory
            
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        
        # Generate plots
        dist_plot_path = os.path.join(output_dir, f"latency_distribution_{timestamp}.png")
        timeline_plot_path = os.path.join(output_dir, f"latency_timeline_{timestamp}.png")
        mode_plot_path = os.path.join(output_dir, f"mode_comparison_{timestamp}.png")
        
        self.plot_latency_distribution(save_path=dist_plot_path)
        self.plot_latency_timeline(save_path=timeline_plot_path)
        self.compare_modes(save_path=mode_plot_path)
        
        # Generate text report
        report_path = os.path.join(output_dir, f"latency_analysis_report_{timestamp}.txt")
        
        with open(report_path, 'w') as f:
            # Redirect print output to file
            import sys
            original_stdout = sys.stdout
            sys.stdout = f
            
            self.print_summary_statistics()
            
            # Restore stdout
            sys.stdout = original_stdout
            
        print(f"\nLatency analysis report generated:")
        print(f"  Report: {report_path}")
        print(f"  Plots: {dist_plot_path}, {timeline_plot_path}, {mode_plot_path}")


def main():
    """Main entry point for the latency analyzer."""
    # Default directory - logs folder in the package
    script_dir = os.path.dirname(os.path.abspath(__file__))
    package_dir = os.path.dirname(script_dir)
    default_csv_dir = os.path.join(package_dir, "logs")
    
    parser = argparse.ArgumentParser(description="Analyze Spot teleoperation latency data")
    parser.add_argument("csv_directory", nargs='?', default=default_csv_dir,
                       help=f"Directory containing latency CSV files (default: {default_csv_dir})")
    parser.add_argument("--output-dir", help="Output directory for analysis results")
    parser.add_argument("--summary-only", action="store_true", 
                       help="Only print summary statistics without generating plots")
    
    args = parser.parse_args()
    
    if not os.path.exists(args.csv_directory):
        print(f"Error: Directory {args.csv_directory} does not exist")
        return 1
        
    try:
        analyzer = LatencyAnalyzer(args.csv_directory)
        analyzer.load_data()
        
        if args.summary_only:
            analyzer.print_summary_statistics()
        else:
            analyzer.generate_report(args.output_dir or args.csv_directory)
            
    except Exception as e:
        print(f"Error during analysis: {e}")
        return 1
        
    return 0


if __name__ == "__main__":
    exit(main())
