# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - spot_arm_controller
    - spot_gripper_controller

  spot_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - arm0_sh0
      - arm0_sh1
      - arm0_el0
      - arm0_el1
      - arm0_wr0
      - arm0_wr1
    action_ns: follow_joint_trajectory
    default: true
  spot_gripper_controller:
    type: GripperCommand
    joints:
      - arm0_f1x
    action_ns: gripper_cmd
    default: true

